import assert from 'node:assert/strict'
import { readFile, readdir, stat } from 'node:fs/promises'

const html = await readFile('dist/index.html', 'utf8')
for (const id of ['about', 'work', 'credentials', 'testimonials', 'contact']) assert(html.includes(`id="${id}"`), `Missing static section ${id}`)
for (const word of ['Microsoft', 'Wipro Infotech', 'Cessna 172', 'Traffic Manager', 'Bastion', 'Azure NAT Gateway', 'Lab experience only']) assert(html.includes(word), `Missing source-grounded content: ${word}`)
assert(html.includes('aria-label="Open Naveed Khan résumé PDF"'))
assert(html.includes('href="/Portfolio/Naveed_Khan_Resume.pdf"'))
assert(html.includes('<details>') && html.includes('<summary>'))
assert(!html.includes('<!--app-html-->'))
assert(!/New Zealand|Auckland|AEWV|sponsorship|Education &amp; languages|JSS PPH/.test(html), 'Private instruction context appeared in public HTML')
assert(html.includes('href="mailto:khannaveed2020@outlook.com"'))
assert(!html.replace(/<[^>]*>/g, '').includes('khannaveed2020@outlook.com'), 'Visible email address appeared')
assert(html.includes('aria-label="Next aviation photo"') && html.includes('aria-label="Next scuba photo"'), 'Missing accessible photo controls')
assert(html.includes('/Portfolio/photos/aviation-06.jpg') && html.includes('/Portfolio/photos/scuba-02.jpg'), 'Missing story photo galleries')
assert(html.includes('id="photography-heading"') && html.includes('aria-label="Next photography photo"'), 'Missing Photography section or control')
assert((html.match(/class="photo-watermark"/g) || []).length === 16, 'Every HBK photo must have its website watermark')
for (let number = 5077; number <= 5092; number++) {
  assert(html.includes(`/Portfolio/photos/photography-${number}.jpg`), `Missing HBK photo ${number}`)
  await stat(`dist/photos/photography-${number}-small.jpg`)
}
assert(html.includes('/Portfolio/credly.svg'), 'Missing local brand logo')
assert(html.includes('<h3 id="credentials-heading"'), 'Credentials must be an explicit heading')
assert(html.includes('RoadLens — Intelligent Car Dashcam'), 'Missing verified project content')
assert(html.includes('Run offline after setup') && html.includes('Keep footage local'), 'Missing README-supported project benefits')
assert(!/Hackathon MVP|Hackathon prototype|View implementation &amp; limitations|Personal introduction in progress/.test(html), 'Removed placeholder or project notice reappeared')
assert(html.includes('<section class="expertise"') && html.includes('id="expertise-heading"'), 'Technical capabilities must be always visible')
assert(!html.includes('<details class="expertise"'), 'Technical capabilities must not be collapsible')
assert(html.includes('<blockquote>') && html.includes('<figcaption>'), 'Testimonials must have semantic quotation and attribution')
assert(html.includes('Ratnavo Dutta') && html.includes('Ankush G'), 'Missing verified recommendation authors')
assert(html.indexOf('id="testimonials"') < html.indexOf('id="contact"'), 'Testimonials must precede Contact')
assert(html.includes('details/recommendations/'), 'Missing LinkedIn recommendation source link')
assert(html.includes('Next testimonial'), 'Missing explicit testimonial control')
assert(!/Pause skills ticker|Resume skills ticker|skills-pause/.test(html), 'Ticker controls removed by user request')
assert(html.includes('Terraform · lab'), 'Skills ticker must preserve lab boundary')
assert(html.includes('logos-track'), 'Missing opposite-direction logo tape')
assert(html.includes('GitHub Copilot') && html.includes('AI Agents') && html.includes('Copilot Studio'), 'Missing user-requested tape skills')
assert(html.indexOf('Ankush G') < html.indexOf('Ratnavo Dutta'), 'Testimonial order must start with Ankush')
for (const logo of ['cisco.svg', 'checkpoint.svg', 'isc2.svg', 'kepner-tregoe.png', 'linuxacademy.png', 'linuxfoundation.svg', 'wireshark.svg']) assert(html.includes(`/logos/${logo}`), `Missing organisation symbol ${logo}`)
assert(html.includes('certifications/az-700.png'), 'Missing authentic certification artwork')
assert(!/historical badge|marked expired|badge-tape-note/.test(html), 'Badge status wording removed by user request')
assert(html.includes('I wish him great success in his career and future roles.'), 'Ratnavo recommendation is truncated')
assert(html.includes('have earned a place/respect'), 'Ankush recommendation is truncated')
const hero = html.slice(html.indexOf('id="about"'), html.indexOf('id="work"'))
assert(!hero.includes('Senior Support Escalation Engineer'), 'Role leaked into personal introduction')
const pdf = await readFile('dist/Naveed_Khan_Resume.pdf')
assert(pdf.subarray(0, 5).toString() === '%PDF-')
assert((await stat('dist/Naveed_Khan_Resume.pdf')).size > 10000)
for (const match of html.matchAll(/(?:src|href)="(\/Portfolio\/[^\"#]+)"/g)) await stat(`dist/${match[1].replace('/Portfolio/', '')}`)
async function audit(path) {
  for (const entry of await readdir(path, { withFileTypes: true })) {
    const file = `${path}/${entry.name}`
    assert(!/\.docx$|master.resume|source-documents/i.test(file), `Private file in output: ${file}`)
    if (entry.isDirectory()) await audit(file)
  }
}
await audit('dist')
console.log('PASS: static content, native details, asset URLs, résumé and public-output privacy checks.')
